# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 囧囧丸
subtitle: ""
description: ""
keywords: [inewsk, inewsk.me, www.inewsk.me, blog, 博客, 囧囧丸]
author: YK
language: zh-TW
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://inewsk.me #https://inewsk.github.io
permalink: post/:title/
permalink_defaults:
  lang: en
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source #存放內容
public_dir: public #生成的站點內容
tag_dir: tags #標籤文件夾
archive_dir: archives #存檔
category_dir: categories #分類
code_dir: downloads/code
i18n_dir: :lang #國際化
skip_render:
  - README.md #跳過指定文件渲染
  - fonts
  - zpix.woff
  - live2d-widget

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0 #1小寫, 2大寫
render_drafts: false
post_asset_folder: true # enable asset file
relative_link: false
future: true
highlight:
  enable: true # hexo 自帶高亮
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: geek

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/INEWSK/inewsk.github.io
  branch: main

# auto generator sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  quotes: "“”‘’"
  modifyAnchors: 0
  anchorAlias: false
  autolink: true
  mangle: true
  sanitizeUrl: false
  headerIds: true
  lazyload: false
  prependRoot: true
  postAsset: true
  external_link:
    enable: false
    exclude: []
    nofollow: false
  disableNunjucks: false
  descriptionLists: true

# https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
# for html
html_minifier:
  enable: false
  ignore_error: false
  silent: false
  exclude:
# for css
css_minifier:
  enable: true
  silent: false
  exclude:
    - "*.min.css"
# for js
js_minifier:
  enable: true
  mangle: true
  silent: false
  # output:
  # compress:
  exclude:
    - "*.min.js"
# for image
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false

js_concator:
  enable: false
  bundle_path: "/js/bundle.js"
  front: false
  silent: false

aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js
