logo_title: INEWSK

style: black

favicon: /favicon.png

menu:
  存檔: /archives
  菊苣錄: /links
  關於: /about
  Github: https://github.com/INEWSK

valine:
  enable: true
  appId: vMDW05AHkvrzuuVo7Pgjri0P-MdYXbMMI
  appKey: fzfb2UU4VBfXr3bH0h2CeUTf

highlight:
  enable: false
